### ISSUE TITLE
sbt: command not found

### ISSUE THREAD

**Issue by n0tel** [hseeberger/scala-sbt#116] opened 2020-08-07 14:16 UTC
Getting error when running container
```
docker run -ti --rm hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.12_2.12.11 /bin/sh
sh-4.2# sbt sbtVersion
sh: sbt: command not found
```

**Comment by francisdb** [comment] 2020-08-07 16:12
Would be great if we could integrate this check in the ci build

**Comment by francisdb** [comment] 2020-11-20 08:13
I can't reproduce this:

```
➜  ~ docker run -ti --rm hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.12_2.12.11 /bin/sh
Unable to find image 'hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.12_2.12.11' locally
graalvm-ce-20.0.0-java11_1.3.12_2.12.11: Pulling from hseeberger/scala-sbt
86607bb85307: Already exists
58a2d320ad14: Already exists
bc84c4167cd4: Already exists
8ab913aa3c80: Already exists
c513467f7f74: Already exists
2689cc2a7f1f: Pull complete
3cbf9a760137: Pull complete
5573774a4bb1: Pull complete
0915458a596c: Pull complete
5014d16940da: Pull complete
8271bbc05f55: Pull complete
025ce3af1d83: Pull complete
Digest: sha256:36ea4909aa953456729356d2e3272b2510d42be9d8ea60f5d3864e41ce1cbfd1
Status: Downloaded newer image for hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.12_2.12.11
sh-4.2# sbt
[info] Updated file /root/project/build.properties: set sbt.version to 1.3.12
[info] welcome to sbt 1.3.12 (Oracle Corporation Java 11.0.6)
[info] loading project definition from /root/project
[info] set current project to root (in build file:/root/)
[info] sbt server started at local:///root/.sbt/1.0/server/27dc1aa3fdf4049b492d/sock
sbt:root> exit
[info] shutting down sbt server
sh-4.2# sbt sbtVersion
[info] welcome to sbt 1.3.12 (Oracle Corporation Java 11.0.6)
[info] loading project definition from /root/project
[info] set current project to root (in build file:/root/)
[info] 1.3.12
sh-4.2#
```

**Comment by francisdb** [comment] 2020-11-20 09:08
@hseeberger you can close this one

**Comment by hseeberger** [comment] 2020-11-20 09:55
Thanks

**Closed by hseeberger** 2020-11-20 09:55 UTC
